apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app     # Name of the Deployment resource
spec:
  replicas: 3         # Number of replica Pods to maintain
  selector:
    matchLabels:
      app: flask-app   # Label selector for Pods
  template:
    metadata:
      labels:
        app: flask-app # Label for Pods created by this Deployment
    spec:
      containers:
      - name: flask-app
        image: barakamwakisha/flask-app:latest  # Docker image to use
        ports:
        - containerPort: 80  # Port the container listens on
