apiVersion: v1
kind: Service
metadata:
  name: flask-service   # Name of the Service resource
spec:
  selector:
    app: flask-app     # Selects Pods with this label
  ports:
    - protocol: TCP
      nodePort: 30200 
      port: 80
      targetPort: 80   # Port the Service forwards traffic to
  type: NodePort   # Type of Service
