apiVersion: v1
kind: Service
metadata:
  name: react-service   # Name of the Service resource
spec:
  selector:
    app: react-app     # Selects Pods with this label
  ports:
    - protocol: TCP
      nodePort: 30100 
      port: 80
      targetPort: 80   # Port the Service forwards traffic to
  type: NodePort   # Type of Service